apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  test99
spec:
  schedule : "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name:  backup
        spec:
          containers:
          - name: centos
            image: freud2187/test:v99
            # args:
            # - /bin/bash
            # - -c
            # - bash /test/copy.sh;
            command: ["bash",  "/test/copy.sh"]
            volumeMounts:
            - mountPath: /var/log/nginx
              name: log
          restartPolicy: OnFailure    
          volumes:
            - hostPath:
                path: /home/freud/log
                type: Directory
              name: log
status: {}




