apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    cloud.google.com/load-balancer-type: "External"
  labels:
    run: nginx
spec:
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  externalTrafficPolicy: Local
  type: LoadBalancer
status:
  loadBalancer:
    ingress: 
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: freud2187/test:v1
        name: nginx
        volumeMounts:
         - mountPath: /var/log/nginx
           name: log
        ports:
        - containerPort: 80
        resources: {}
      volumes:
        - hostPath:
           path: /home/freud/log
           type: Directory
          name: log
status: {}